name: Deploy MARP presentation to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (required for marp-cli)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install marp-cli
        run: npm install -g @marp-team/marp-cli

      - name: Build HTML presentation
        run: marp doc/raport.md --html -o doc/index.html

      - name: Build PDF presentation
        run: marp doc/raport.md --pdf -o doc/raport.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: raport-pdf
          path: doc/raport.pdf

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
